baseURL: https://joonparkhere.netlify.app/
title: joonparkhere's blog

languageCode: ko-kr
DefaultContentLanguage: ko  # Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
hasCJKLanguage: true

googleAnalytics: G-KT1233XP5V

enableRobotsTXT: true

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

pygmentsCodeFences: true
pygmentsUseClasses: true

# staticDir:
#   - assets

ignoreFiles:
  - project/*

module:
  hugoVersion:
    extended: true
    min: 0.87.0

# markup:
#   goldmark:
#     extensions:
#       definitionList: true
#       footnote: true
#       linkify: true
#       strikethrough: true
#       table: true
#       taskList: true
#     renderer:
#       unsafe: false # Set to true if you have HTML content inside Markdown
#     tableOfContents:
#       endLevel: 3
#       ordered: false
#       startLevel: 2
#     highlight:
#       anchorLineNos: true
#       codeFences: true
#       guessSyntax: false
#       hl_Lines: ""
#       lineAnchors: ""
#       lineNoStart: 1
#       lineNos: true
#       lineNumbersInTable: true
#       noClasses: true
#       style: native
#       tabWidth: 4

params:
  author: Seungho Park
  description: sample description
  github: joonparkhere
  # facebook:
  # twitter:
  # linkedin:
  # instagram:
  # tumblr:
  email: tmdgh0221@gmail.com
  # url:
  keywords: sample keywords
  rss: false
  lastmod: true
  favicon: "/images/github.png"
  location: Korea
  userStatusEmoji: 😶
  # links:
  #   - title: link A
  #     href: https://github.com/joonparkhere
  #   - title: link B

frontmatter:
  lastmod:
    - lastmod
    - :fileModTime
    - :default

# related:
#   includeNewer: true
#   threshold: 30
#   toLower: false
#   indices:
#     - name: tags
#       weight: 100
#     - name: categories
#       weight: 200 